### PR TITLE
Deinhofer/resolve port conflicts

### PR DESCRIPTION
**Pull request by deinhofer**
This PR automatically resolves port conflicts (ACS or REST ports) in case of multiple ARE instances.

If a port is already busy, try to find another one. The new port is calculated as follows:
 ```java
int NR_TRIES_PORT=3;
int PORT_STEP_SIZE=5;

for (int i=0;i<NR_TRIES_PORT;i++) {
  int port=port+i*PORT_STEP_SIZE;

  if(bind(port)==true) {
    break;
  }
}
```
This is done for the old ACS ports (9090, 9091 UDPServer) and REST ports (http=8081,ws=8082,https=8083).
Pressing <kbd>F8</kbd> automatically opens the WebACS of the corresponding ARE and opens the model of it.

To know which ARE has which ports, the title of the ARE shows the initial port numbers, e.g.
image

### CODE REVIEW

**Comment by ChrisVeigl** [comment]
thanks for adding this functionality!
very useful to run multiple ARE-based tools at the same time!

**Comment by deinhofer** [comment]
> thanks for adding this functionality!
> very useful to run multiple ARE-based tools at the same time!

Thanks!! The error message was really annoying already :-)
I will merge now.

**Comment by klues** [comment]
Great! :)
Also very useful for AsTeRICS Grid to have the possibility of multiple instances for input events and performed actions (e.g. environmental control). Are these ports also are configurable by `are.properties`?

**Comment by deinhofer** [comment]
> Great! :)
> Also very useful for AsTeRICS Grid to have the possibility of multiple instances for input events and performed actions (e.g. environmental control). Are these ports also are configurable by `are.properties`?

Yes, the 2 variables can be configured in areProperties

**Pull request merged**
