### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by klues**

### CODE REVIEW

**Comment by klues** [comment]
I've used the `improve this page` function -> why this is now a pull request on the AsTeRICS repository and not on the AsTeRICS Docs repository?

**Comment by deinhofer** [comment]
> I've used the `improve this page` function -> why this is now a pull request on the AsTeRICS repository and not on the AsTeRICS Docs repository?

Because the contents is created and versioned at the respective repository, e.g. contents or a tutorial related to the ARE is created in the AsTeRICS repository, manuals of the WebACS in the WebACS repository. Also if someone creates a pull request to the respective repository he/she can inlcude an update of the respective manuals/tutorials according to the change.

**Comment by klues** [comment]
however, in order to not only point out the negative things, Chris liked the collected documentation on the new page very much :)

**Comment by sabicalija** [comment]
Hi there,

I've reopened this PR again. Maybe we should open a new PR in asterics-docs. But for now, let's keep this open until the new is here... :grin:

I agree with the phrasing. I'm sure, it is well-intentioned, but many might feel offended by it.

---

I also think, that the content that is display when clicking 'Get Started' should be placed somewhere at the start page, i.e., this



goes (somewhere) there:

grafik

---

Clicking 'Get Started' should show the installations page immediately.

**Pull request closed without merging**
