### PR TITLE
Bklaus/adding send data input port to restapi

### PR DESCRIPTION
**Pull request by deinhofer**
@mariokom Could you please review it regarding REST conventions? Is the path correct? What else must be considered? Documentation?

The code in method [AsapiSupport.sendData](https://github.com/asterics/AsTeRICS/compare/master...klues:bklaus/adding-send-data-input-port-to-restapi?expand=1#diff-2bea9000d459716d222d3942ae4ad681R1514) must be executed within the model executor lifecycle thread and be wrapped with this method: https://github.com/asterics/AsTeRICS/blob/master/ARE/middleware/src/main/java/eu/asterics/mw/services/AstericsModelExecutionThreadPool.java#L254

### CODE REVIEW

**Comment by mariokom** [comment]
@deinhofer i will be able to test it on the next week. Just by looking at it seems very good.

**Comment by klues** [comment]
I've wrapped my code in the method @deinhofer suggested to execute it in in the model executor lifecycle.

**Comment by deinhofer** [comment]
Sorry I was a bit fast with merging, but I wanted to have it in, before the code reformatting....
Some TODOS I got in mind:

* Data format of data sent to the input port:
It comes as String, but what if the target port expects a different data type?
--> Automatically convert the String into the target format, as it is done here: https://github.com/asterics/AsTeRICS/blob/master/ARE/middleware/src/main/java/eu/asterics/mw/model/runtime/impl/AbstractRuntimeOutputPort.java#L74

* Add function to javascript lib
* Update REST API documentation
* Add example

* Do the same for event triggering??!?

**Comment by mariokom** [comment]
Some comments regarding the new function that was added in the API:

The current URI is this:
/runtime/model/components/input/{componentId}/{inputKey}

Please consider these comments:
- By including the "input" after the "components", it is semantically equivalent to "the components of type input". In this case we want input ports, not input components.
- Please avoid putting data to the actual URI. In most of the cases, the URI should only be an identifier of the resource and the data should be moved to the HTTP body. Hence, IMHO the {inputKey} should be moved.

So, to be inline with the rest of the API calls, i think the REST URI for sending data to a port should look like this: 
"/runtime/model/components/{componentId}/ports/{portId}/data"
or this, if we want to distincs input from output ports
"/runtime/model/components/{componentId}/ports/input/{portId}/data"

**Comment by klues** [comment]
made new pull request renaming the REST-path as mario suggested and adding datatype conversion as martin suggested.

**Pull request merged**
