### PR TITLE
prevent crash if setOpacity not supported

### LINKED ISSUE #318: CrossHair/Tooltip Plugin won't start: "TRANSLUCENT translucency is not supported"
If I try to start a model with the crosshair plugin, it won't start.
Error message:
Screenshot from 2019-05-09 14-48-16

System:
Debian Stretch (stable), x86-64
Cinnamon Desktop (lightdm)
AsTeRICS 4.0.0-alpha1

### PR DESCRIPTION
**Pull request by klues**
fixes #318

### CODE REVIEW

**Comment by benjaminaigner** [comment]
There was an additional exception, but now it works.

**Comment by klues** [comment]
I just replaced the two catch clauses with one for catching all possible exceptions - shorter and safer ;)
Please try once again.

**Comment by benjaminaigner** [comment]
Works fine!

**Comment by klues** [comment]
great, I'll merge.

**Pull request merged**
